

  const AllDbData = {

    //all admission_status pending students
    EnquiryData:{
      EnquiryPendingData:[
        {
          enquiry_id:"SS01",
          name:"ajay",
          phone:"224434334",
          batch:"Web Design",
          gender:"female",
          address:"word 2 jaipur",
          date:"12/03/2020",
          demo_status:"Done",
          admission_status:"Pending",
        
        },
        {
            enquiry_id:"SS02",
            name:"ajay",
            phone:"224434334",
          batch:"RS-CIT",
          gender:"male",
          address:"word 2 , anupgarh",
          date:"12/03/2024",
            demo_status:"Pending",
            admission_status:"Pending",
          },
          {
            enquiry_id:"SS02",
            name:"sonu",
            phone:"224434334",
          batch:"rscit",
          gender:"male",
          address:"word 2 , anupgarh",
          date:"12/03/2024",
            demo_status:"Pending",
            admission_status:"Pending",
          },
        
      ],
      EnquiryDoneData:[
        {
          enquiry_id:"SS01",
          name:"ajay",
          phone:"224434334",
          batch:"rscit",
          gender:"male",
          address:"word 2 anupgarh",
          date:"12/03/2024",
          demo_status:"Done",
          admission_status:"Done",
        
        },
        {
            enquiry_id:"SS02",
            name:"ajay",
            phone:"224434334",
          batch:"rscit",
          gender:"male",
          address:"word 2 , anupgarh",
          date:"12/03/2024",
            demo_status:"Done",
            admission_status:"Done",
          },
          {
            enquiry_id:"SS02",
            name:"sonu",
            phone:"224434334",
          batch:"rscit",
          gender:"male",
          address:"word 2 , anupgarh",
          date:"12/03/2024",
            demo_status:"Done",
            admission_status:"Done",
          },
        
      ],
    },
    
    DemoData:[
      {
        demo_id:"SS01",
        name:"ajay",
        phone:"224434334",
        batch:"rscit",
        gender:"male",
        address:"word 2 , anupgarh",
        date:"12/03/2024",
        addmission_status:"yes",
      
      },
      {
        demo_id:"SS02",
        name:"ajay",
        phone:"224434334",
        batch:"rscit",
        gender:"male",
        address:"word 2 , anupgarh",
        date:"12/03/2024",
        addmission_status:"yes",
        },
        {
          demo_id:"SS02",
          name:"ajay",
          phone:"224434334",
          batch:"rscit",
          gender:"male",
          address:"word 2 , anupgarh",
          date:"12/03/2024",
          addmission_status:"yes",
          },
          {
            demo_id:"SS02",
            name:"ajay",
            phone:"224434334",
            batch:"rscit",
            gender:"male",
            address:"word 2 , anupgarh",
            date:"12/03/2024",
            addmission_status:"yes",
            },
            {
              demo_id:"SS02",
              name:"ajay",
              phone:"224434334",
              batch:"rscit",
              gender:"male",
              address:"word 2 , anupgarh",
              date:"12/03/2024",
              addmission_status:"yes",
              },
        
      
    ],
    AllStudentData:[
      {
        student_id:"SS01",
        name:"ajay Goswami",
        phone:"224434334",
        relative_roll:"S/o.",
        relative_name:"test ji",
        relative_phone:"63535555555",
        photo:"mypic.png",
        address:"word 2 , anupgarh",
        dob:"12/02/21",
        batch:"rscit",
        joining_date:"12/02/22",
        course_validity:"2 months",
        course_validity_date:"11/02/2025",
        total_fee:"10000",
        paid_fee:"2000",
        gender:"male",
        pending_fee:"100",
      
      },
      {
        student_id:"SS02",
        name:"ajay",
        phone:"224434334",
        relative_roll:"D/o.",
        relative_name:"test ji",
        relative_phone:"mypic.png",
        photo:"mypic.png",
        address:"word 2 , anupgarh",
        dob:"12/02/21",
        batch:"rscit",
        joining_date:"12/02/22",
        course_validity:"2 months",
        course_validity_date:"11/02/2025",
        total_fee:"10000",
        paid_fee:"2000",
        gender:"male",
        pending_fee:"1110",
        },
        {
          student_id:"SS03",
          name:"ajay",
          phone:"224434334",
          relative_roll:"W/o.",
          relative_name:"sdffsfsdf sdfs",
          relative_phone:"mypic.png",
          photo:"mypic.png",
          address:"word 2 , anupgarh",
          dob:"12/02/21",
          batch:"rscit",
          joining_date:"12/02/22",
          course_validity:"2 months",
          course_validity_date:"11/02/2025",
          total_fee:"10000",
          paid_fee:"2000",
          gender:"male",
          pending_fee:"150",
          },
          {
            student_id:"SS02",
            name:"ajay",
            phone:"224434334",
            relative_roll:"S/o.",
            relative_name:"test ji",
            relative_phone:"mypic.png",
            photo:"mypic.png",
            address:"word 2 , anupgarh",
            dob:"12/02/21",
            batch:"rscit",
            joining_date:"12/02/22",
            course_validity:"2 months",
            course_validity_date:"11/02/2025",
            total_fee:"10000",
            paid_fee:"2000",
            gender:"male",
            pending_fee:"1220",
            },
            {
              student_id:"SS02",
              name:"ajay",
              phone:"224434334",
              relative_roll:"S/o.",
              relative_name:"test ji",
              relative_phone:"mypic.png",
              photo:"mypic.png",
              address:"word 2 , anupgarh",
              dob:"12/02/21",
              batch:"rscit",
              joining_date:"12/02/22",
              course_validity:"2 months",
              course_validity_date:"11/02/2025",
              total_fee:"10000",
              paid_fee:"2000",
              gender:"male",
              pending_fee:"110",
              },
              {
                student_id:"SS02",
                name:"ajay",
                phone:"224434334",
                relative_roll:"S/o.",
                relative_name:"test ji",
                relative_phone:"mypic.png",
                photo:"mypic.png",
                address:"word 2 , anupgarh",
                dob:"12/02/21",
                batch:"rscit",
                joining_date:"12/02/22",
                course_validity:"2 months",
                course_validity_date:"11/02/2025",
                total_fee:"10000",
                paid_fee:"2000",
                gender:"male",
                pending_fee:"10",
                },
                {
                  student_id:"SS02",
                  name:"ajay",
                  phone:"224434334",
                  relative_roll:"S/o.",
                  relative_name:"test ji",
                  relative_phone:"mypic.png",
                  photo:"mypic.png",
                  address:"word 2 , anupgarh",
                  dob:"12/02/21",
                  batch:"rscit",
                  joining_date:"12/02/22",
                  course_validity:"2 months",
                  course_validity_date:"11/02/2025",
                  total_fee:"10000",
                  paid_fee:"2000",
                  gender:"male",
                  pending_fee:"1550",
                  },
                  {
                    student_id:"SS02",
                    name:"ajay",
                    phone:"224434334",
                    relative_roll:"S/o.",
                    relative_name:"test ji",
                    relative_phone:"mypic.png",
                    photo:"mypic.png",
                    address:"word 2 , anupgarh",
                    dob:"12/02/21",
                    batch:"rscit",
                    joining_date:"12/02/22",
                    course_validity:"2 months",
                    course_validity_date:"11/02/2025",
                    total_fee:"10000",
                    paid_fee:"2000",
                    gender:"male",
                    pending_fee:"1055",
                    },
                    
        
      
    ],
    CourseValidity : ["1 Month", "2 Month", "6 Month", "1 Year"],
    RelativeRolls:["S/o.","D/o.","W/o."],
    AllCourse:["RS-CIT", "Web Design", "Web Development", "Java"],
    
    TodayPendingFee:[
      {
        student_id:"SS01",
        name:"Seema",
        relative_name:"ajay",
        relative_roll:"W/o.",
        phone:"224434334",
        course_validity:"2 months",
        total_fee:"10000",
        Due_fee:"10000",
        paid_fee:"2000",
        pending_fee:"10",
      
      },
      {
          student_id:"SS01",
          name:"ajay",
          relative_name:"darmveer",
          relative_roll:"S/o.",
          phone:"224434334",
          course_validity:"2 months",
          total_fee:"10000",
          Due_fee:"10000",
          paid_fee:"2000",
          pending_fee:"10",
        },
        
      
    ],
    OwnerProfile:[
      {
        center_code:"SS01",
        owner_name:"ajay Goswami",
        owner_phone:"224434334",
        center_phone:"224434334",
        center_name:"Stomer Study",
        center_address:"word 2 , anupgarh",
        joining_date:"12/02/22",
      },
    ]
    
  }
    export default AllDbData;